INSERT INTO PARTIDOS (PRT_NOME, PRT_SIGLA) VALUES ('Partido dos Trabalhadores', 'PT');
INSERT INTO PARTIDOS (PRT_NOME, PRT_SIGLA) VALUES ('Partido da Social Democracia Brasileira', 'PSDB');
INSERT INTO PARTIDOS (PRT_NOME, PRT_SIGLA) VALUES ('Partido Comunista Brasileiro', 'PCB');
INSERT INTO PARTIDOS (PRT_NOME, PRT_SIGLA) VALUES ('Partido da Causa Operária', 'PCO');
INSERT INTO PARTIDOS (PRT_NOME, PRT_SIGLA) VALUES ('Partido Liberal', 'PL');

INSERT INTO POLITICOS (PLT_TIPO_CANDIDATURA, PLT_INICIO_MANDATO, USR_NOME, USR_SEXO, USR_DATA_NASCIMENTO, USR_EMAIL, USR_CPF, USR_SENHA, FK_PARTIDOS_PRT_ID)
VALUES ('Vereador(a)', '2000-01-01', 'Nome do Candidato', 'M', '1800-01-01', 'eduardo@gmail.com', '12345678901', '123456', 1);



